// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
  const { Sequelize } = sequelize;
  // This section contains the fields of your model, mapped to your table's columns.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const Categories = sequelize.define('categories', {
    title: {
      type: DataTypes.STRING,
    },
    position: {
      type: DataTypes.INTEGER,
    },
    iconFileName: {
      type: DataTypes.STRING,
    },
    iconContentType: {
      type: DataTypes.STRING,
    },
    iconFileSize: {
      type: DataTypes.INTEGER,
    },
    iconUpdatedAt: {
      type: DataTypes.DATE,
    },
    createdAt: {
      type: DataTypes.DATE,
    },
    updatedAt: {
      type: DataTypes.DATE,
    },
  }, {
    tableName: 'categories',
    underscored: true,
    schema: process.env.DATABASE_SCHEMA,
  });

  // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
  Categories.associate = (models) => {
    Categories.belongsTo(models.categories, {
      foreignKey: {
        name: 'categoryIdKey',
        field: 'category_id',
      },
      as: 'category',
    });
    Categories.belongsTo(models.categories, {
      foreignKey: {
        name: 'mainCategoryIdKey',
        field: 'main_category_id',
      },
      as: 'mainCategory',
    });
    Categories.hasMany(models.genericProducts, {
      foreignKey: {
        name: 'categoryIdKey',
        field: 'category_id',
      },
      as: 'genericProducts',
    });
    Categories.hasMany(models.categories, {
      foreignKey: {
        name: 'categoryIdKey',
        field: 'category_id',
      },
      as: 'categories',
    });
    Categories.hasMany(models.categories, {
      foreignKey: {
        name: 'mainCategoryIdKey',
        field: 'main_category_id',
      },
      as: 'mainCategoryCategories',
    });
  };

  return Categories;
};
